name: cool-action
on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]
jobs:
  build-and-run-linux:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: build-and-run
     run: sh hello-world
       
  build-and-run-mac:
   runs-on: macos-latest
   steps:
   - uses: actions/checkout@v3
   - name: build-and-run
     run: sh hello-world 
